on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: deps
      run: go mod download
    - name: build
      run: |
        GOARCH=arm64 make --always-make module.tar.gz && mv module.tar.gz module-arm64.tar.gz
        GOARCH=amd64 make --always-make module.tar.gz && mv module.tar.gz module-amd64.tar.gz
    - uses: viamrobotics/upload-module@main
      # note: this workflow no long has an 'on: release' trigger. see ./build.yml
      if: github.event_name == 'release'
      with:
        module-path: module-arm64.tar.gz
        platform: linux/arm64
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module-amd64.tar.gz
        platform: linux/amd64
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
